name: CI/CD for Angular

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.1.2

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration=production

      - name: Run Tests
        run: npm run test
