name: CI

on:
  push:
    branches: [main , github-actions ]
  pull_request:
    branches: [main , github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.1.2

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --prod

      - name: Run Tests
        run: ng test
